- name: Demo on Loops
  hosts: localhost
  conection: local
  tasks:
    -name: Demo on Loops
     ansible.builtin.debug:
       msg: Fruit Name - {{ item }}
     loop:
      - apple
      - banana
      - orange


